### ISSUE TITLE
Feature request: make it PyPi package or at least 'pip installable' from github repository

### ISSUE THREAD

**Issue by tector** [gmontamat/pyaw-reporting#1]
We actively use PyAwReporting as a library in our project(s) and like it! But it is a bit futile to download the files additionally to our 'pip install' workflow because 'pip install' is not possible:

```
$ pip install pyawreporting
Collecting pyawreporting
  Could not find a version that satisfies the requirement pyawreporting (from versions: )
No matching distribution found for pyawreporting
```

Also we have to patch the code in awreporting.py just a little, because we do not want to store queries in files but serve them as a parameter:

```python
def read_query(query_file):
    
    if os.path.isfile(query_file):

        try:
            with open(query_file, 'rb') as fin:
                query = fin.read().replace('\r', '').replace('\n', ' ')
        except Exception as e:
            logger.exception("Couldn't read query file")
            sys.exit(1)

    else:

        # if it is not a file it is maybe a query string
        query = query_file

    return query
```

**Comment by gmontamat** [comment]
Nice to hear that it's being used. We'll work on those!

**Comment by gmontamat** [comment]
@tector to maintain backwards compatibility I'll keep -q FILE and add a mutually exclusive param -a/--awql "QUERY" to call awreporting.py with the passed query.
btw, how about using a default value in -t TOKEN too? I remember credentials were stored somewhere in the home dir by default when generated, right?

**Comment by tector** [comment]
I thought that my suggested code change above is already backwards compatible, but i do not know the details of all usecases. :)

Our usecase does not require the use of command line. We just import pyawreporting as a python library and use the function get_report() with the AWQL query and filepath to the token file. The token file varies for each customer. So we do not use a default token file.

But i agree that it would be nice, if you can omit the token parameter in case that the token file is located in current working directory or (as a fallback) in the home directory. 👍

**Comment by gmontamat** [comment]
Got you! I'm thinking about using the actual query as a parameter of get_report() and parse the query file beforehand if needed with the read_query() function. I understand this won't affect the way you use the get_report() function. Take a look at the [dev-query](https://github.com/gmontamat/pyaw-reporting/tree/dev-query) branch.

**Comment by tector** [comment]
Yeah, looks good to me! 👍

**Comment by gmontamat** [comment]
I guess it's almost ready for pip now. I'll update README's installation steps when I upload it there.
@tector please check get_report() now that use of logging has been improved too.

**Comment by tector** [comment]
Looks good.
I currently try to use PyAwReporting in another project which is using Flask and i have a weird problem with the import (which is not an issue with PyAwReporting but with the Flask framework i guess). So i am looking forward to the 'pip install' feature and hope it can solve the problem :)

**Comment by gmontamat** [comment]
Ok! i'm going to test it as a library too since the original idea for PyAwReporting (started a while ago) was for it to be called from the terminal.

**Comment by gmontamat** [comment]
@tector 
```
pip install pyaw-reporting
```
and you can use it like this:
```
from awreporting import get_report

query = (
    "SELECT ExternalCustomerId, CampaignId, AdGroupId, Id, Date, Clicks, Impressions "
    "FROM AD_PERFORMANCE_REPORT "
    "WHERE Impressions > 0 "
    "DURING LAST_7_DAYS"
)
get_report('example.yaml', query, 'adperformance.csv', 100)
```
Again, I did change the structure a bit to make it a proper python module (without losing the command line feature which was the original purpose, in fact it was enhanced). Please test it and let me know how it goes.

**Comment by tector** [comment]
Works great, so far! 👍

**Comment by gmontamat** [comment]
Closing this issue :). If you find a bug in the package, feel free to create a new one.
For future reference the version you're using can be installed with
```
pip install pyaw-reporting==0.0.2
```
Just in case I happen to break backwards code compatibility in future releases.
