### ISSUE TITLE
get nothing from AD_PERFORMANCE_REPORT

### ISSUE THREAD

**Issue by xiaojieliu7** [gmontamat/pyaw-reporting#4]
`from awreporting import get_report

query = (
    "SELECT ExternalCustomerId, CampaignId, AdGroupId, Id, Date, Clicks, Impressions "
    "FROM AD_PERFORMANCE_REPORT "
    "WHERE Impressions > 0 "
    "DURING LAST_7_DAYS"
)
get_report('example.yaml', query, 'adperformance.csv', 100)`
When I use the code below, nothing return. 
But when I try to get the CAMPAIGN_PERFORMANCE_REPORT for the same client with the same date range, I get some rows.

**Comment by gmontamat** [comment]
Hi @xiaojieliu7 could you please provide the release you're using for googleads and pyaw-reporting?
You can check those using `pip freeze`.
I'll test the AD_PERFORMANCE_REPORT on my end

Check `awreporting.log` also, there may be more insights on your issue there.

**Comment by xiaojieliu7** [comment]
googleads  15.0.2
pyaw-reporting 0.0.4

thanks, I have test by using AdWordsClient.GetReportDownloader(version='v201809').DownloadReport, but also get nothing

**Comment by gmontamat** [comment]
Please try:
`pip install --upgrade googleads`
pyaw-reporting is compatible with the latest version `googleads 18.1.0`. It is very likely the case that your googleads version doesn't support the api version `v201809`. Any findings in `awreporting.log`?

**Comment by gmontamat** [comment]
@xiaojieliu7 I was not able to reproduce your problem. Even `googleads 15.0.2` works fine with awreporting. Please check `awreporting.log` after you run the AD_PERFORMANCE_REPORT. It could be a problem with your credentials.
